apiVersion: v1
kind: Service
metadata:
  name: http-echo
  labels:
    app: http-echo
spec:
  selector:
    app: http-echo
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
