name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: define hash
        run: echo ::set-env name=SHA8::$(GITHUB_SHA::8)
      - name: Build container image with Gradle
        run: |
          echo "${SHA8}"
          ./gradlew :bootBuildImage --imageName="tkak/java-http-echo:${SHA8}"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tkak/java-http-echo
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.SHA8 }}"
