name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build container image with Gradle
        run: |
          ./gradlew :bootBuildImage --imageName="docker.pkg.github.com/${{ github.actor }}/java-http-echo/java-http-echo:${{ github.sha }}"
      - name: Publish to Registry
        run: |
          docker login https://docker.pkg.github.com -u ${{secrets.DOCKER_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push "docker.pkg.github.com/${{ github.actor }}/java-http-echo/java-http-echo:${{ github.sha }}"
